### ISSUE TITLE
Math Magicians: refactor with hooks

### ISSUE THREAD

**Issue by rica213** [rica213/math-magicians#4]
The 'Calculator' component is already a functional component.
While implementing the logic to the calculator, I used the **useState** hook to add a state to the calcObj and to display the computed value on my screen. Here's the code snippet initializing the state :
<code>
  const [total, setTotal] = useState(null);
  const [next, setNext] = useState(null);
  const [operation, setOperation] = useState(null);
  const [screenValue, setScreenValue] = useState('0');
</code>

To be able able to use the **useState** hook, you need to import it first. Like this:

<code>import React, { useState } from 'react';</code>

Inside my handler function I used the **setTotal**, **setNext**, **setOperation**, and **setScreenValue**

<code>  const handleCalc = (e) => {
    ...
    setTotal(newCalcObj.total);
    setNext(newCalcObj.next);
    setOperation(newCalcObj.operation);
    setScreenValue(newCalcObj.next || newCalcObj.total || '0');
  };</code>

**Comment by elisha2kyakpo1** [comment]
Hi 👋 @rica213, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

✔️ The project uses a functional component.
👍 The description of a functional component is clear.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
